### ISSUE TITLE
Move Hikari DB creation logic to Bootstrap

### ISSUE THREAD

**Issue by Asitha** [wso2/product-mi-tooling#126]
**Description:**

Move the Hikari database pooling creation logic in Bootstrap class. Use JNDI InitialContext based approach to get the Datasource object from the Dashboard Core component.

**Comment by dulanjalidilmi** [comment]
Closing this issue since we are in the progress of removing the database from MI Dashboard[1].

[1] https://github.com/wso2/api-manager/issues/508
