### ISSUE TITLE
Add auto autocomplete for user name and password support in the monitor dashboard

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-mi-tooling#163]
**Description:**
The auto-fill user name/password on the login page using the browser caching and history is not supported in the micro integrator dashboard. 
Ex: 
![image](https://user-images.githubusercontent.com/37293166/109930176-59c35900-7ced-11eb-91d8-20663d372948.png)

**Suggested Labels:**

**Affected Product Version:**
wso2mi-monitoring-dashboard-1.2.0

**Comment by tharakamd** [comment]
This issue is fixed with the PR: https://github.com/wso2/product-mi-tooling/pull/156
